### PR TITLE
patch for Qt6 build

### PR DESCRIPTION
**Pull request by Sportacandy**
Quick patch for Qt6 build. Confirmed that SMPlayer can be built with Qt6.8.3+minGW13.1.0 and Qt5.15.2+minGW12.0.0, and both are working well.

### CODE REVIEW

**Comment by smplayer-dev** [comment]
Thank you so much.

Unfortunately it fails to compile in my computer (Ubuntu, Qt 6.2.4):
```

In file included from prefinterface.h:22,
                 from preferencesdialog.cpp:25:
.ui/ui_prefinterface.h: In member function ‘void Ui_PrefInterface::setupUi(QWidget*)’:
.ui/ui_prefinterface.h:834:25: error: no matching function for call to ‘QObject::connect(QSlider*&, void (QAbstractSlider::*)(int), QLabel*&, <unresolved overloaded function type>)’
  834 |         QObject::connect(floating_width_slider, &QSlider::valueChanged, floating_width_label, &QLabel::setNum);
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qvariant.h:51,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/QVariant:1,
                 from .ui/ui_preferencesdialog.h:12,
                 from preferencesdialog.h:22,
                 from preferencesdialog.cpp:20:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qobject.h:217:43: note: candidate: ‘template<class Func1, class Func2> static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType)’
  217 |     static inline QMetaObject::Connection connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal,
      |                                           ^~~~~~~
/usr/include/x86_64-linux-gnu/qt6/QtCore/qobject.h:217:43: note:   template argument deduction/substitution failed:
In file included from prefinterface.h:22,
                 from preferencesdialog.cpp:25:
.ui/ui_prefinterface.h:834:25: note:   couldn’t deduce template parameter ‘Func2’
  834 |         QObject::connect(floating_width_slider, &QSlider::valueChanged, floating_width_label, &QLabel::setNum);
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qvariant.h:51,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/QVariant:1,
                 from .ui/ui_preferencesdialog.h:12,
                 from preferencesdialog.h:22,
                 from preferencesdialog.cpp:20:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qobject.h:249:13: note: candidate: ‘template<class Func1, class Func2> static typename std::enable_if<((int)(QtPrivate::FunctionPointer<Func2>::ArgumentCount) >= 0), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, Func2)’
  249 |             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, Func2 slot)
      |             ^~~~~~~
/usr/include/x86_64-linux-gnu/qt6/QtCore/qobject.h:249:13: note:   template argument deduction/substitution failed:
In file included from prefinterface.h:22,
                 from preferencesdialog.cpp:25:
.ui/ui_prefinterface.h:834:25: note:   candidate expects 3 arguments, 4 provided
  834 |         QObject::connect(floating_width_slider, &QSlider::valueChanged, floating_width_label, &QLabel::setNum);
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qvariant.h:51,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/QVariant:1,
                 from .ui/ui_preferencesdialog.h:12,
                 from preferencesdialog.h:22,
                 from preferencesdialog.cpp:20:

```
And a lot of similar errors.

**Comment by Sportacandy** [comment]
Qt 6.2 is too different from recent Qt releases such as Qt 6.8.x. The reason why I used Qt 6.8 is that It's the latest LTS.
I recommend updating the Qt to Qt6.8.x to apply my patch.

**Comment by smplayer-dev** [comment]
I've just applied your patch and fixed the compiling problems with Qt 6.2 in this branch:
https://github.com/smplayer-dev/smplayer/tree/qt6

**Comment by Raza-0007** [comment]
Ricardo, I am assuming you chose Qt 6.2 for better compatibility with Qt 5.15 as explained in [this article](https://www.qt.io/blog/qt-6.2-lts-released). But the problem is that Qt 6.2 LTS went [out of support](https://www.qt.io/blog/commercial-lts-qt-6.2.13-released) on September 2024, no bug fixes or security patches since then, so we are back in the same boat as we were with Qt 5.15! 

It would be better to choose Qt 6.8 LTS [released on October 2024](https://www.qt.io/blog/qt-6.8-released), as it will be supported for 5 years until September 2029. A little effort now will ensure next 5 years of peace :wink:

**Comment by smplayer-dev** [comment]
It's not a matter of choice, it's just that Linux distros include old versions of Qt.

**Comment by a17r** [comment]
@smplayer-dev These distro (versions) are unlikely to ever package a future Qt6-based version of smplayer and they won't drop the Qt5-based version either. If you are looking at release-based distributions for Qt support choice, near-term upcoming distro releases should be your target. That gives you the freedom to straighten up at least the *latest* ifdef offshoots in an ever-growing jungle.

**Comment by Raza-0007** [comment]
I am not a developer, but for an open source software like smplayer, you should be able to download Qt 6.8 LTS for Linux directly from the Qt website. You should not have to depend on your Linux distros built-in Qt.

Just go to the [official open source Qt download site](https://www.qt.io/download-qt-installer-oss). Choose the online installer, it will guide you step-by-step, choose Qt 6.8.x and required modules, and since smplayer is open source, licensing should be taken care of as well. That should be all one needs to compile smplayer with Qt 6.8.x, unless I am missing something, as I mentioned previously, I am not a developer.

**Comment by maverick74** [comment]
> @smplayer-dev These distro (versions) are unlikely to ever package a future Qt6-based version of smplayer and they won't drop the Qt5-based version either. If you are looking at release-based distributions for Qt support choice, near-term upcoming distro releases should be your target. That gives you the freedom to straighten up at least the _latest_ ifdef offshoots in an ever-growing jungle.

I'm with @a17r on this! Supporting the last LTS does make sense, but older than that is crazy! 

If a distro wants to keep software that old it should be their job to do so! Or they can always use the last player version that was compatible with it!

Software devs, from my pov, should only care about the latest stable release and latest LTS! (naturally, while developing, the target is always master/vanilla)... but this is "my" view of it! I'm not dictating anything! Each dev chooses!
But the line has to be drawn somewhere (or risk going crazy ahah)

**Comment by Raza-0007** [comment]
I posted a brief [feedback for the Qt 6.8 version of smplayer for Windows OS](https://github.com/smplayer-dev/smplayer/issues/632#issuecomment-3272619373) in Qt6 Roadmap thread, I thought I should link it here as well in case someone is following this thread and not the other one.

**Comment by VVD** [comment]
> Quick patch for Qt6 build. Confirmed that SMPlayer can be built with Qt6.8.3+minGW13.1.0 and Qt5.15.2+minGW12.0.0, and both are working well.

Why replace tabs with spaces in patch?

**Comment by Sportacandy** [comment]
> Why replace tabs with spaces in patch?

Oh, no special reason, just due to my preference for QtCreator("Default tab policy").

**Comment by a17r** [comment]
@Sportacandy Formatting changes should never be intermingled with substantial changes. Existing formatting, indendation, basic coding style, should be adhered to, just as we expect uniform line endings.

Ideally of course, the upstream project would define an `.editorconfig` that would automatically bind your QtCreator instance to its will.

**Comment by VVD** [comment]
Friendly ping. :-)

**Comment by sergiomb2** [comment]
Hi, I am using the https://github.com/smplayer-dev/smplayer/tree/qt6 branch. I think this should go there.

File: src/globalshortcuts/globalshortcuts_win.cpp [hunk 1]
```diff
@@ -17,9 +17,17 @@
...
+#include <QDebug>
+#if QT_VERSION_MAJOR >= 6
+#include "globalshortcuts.h"
+#endif
 
+#if QT_VERSION_MAJOR < 6
 bool GlobalShortcuts::nativeEventFilter(const QByteArray & /*eventType*/, void * message, long * /*result*/) {
-	//qDebug() << "GlobalShortcuts::nativeEventFilter";
+#else
+bool GlobalShortcuts::nativeEventFilter(const QByteArray & /*eventType*/, void * message, qintptr * /*result*/) {
```
Comment (stefantalpalaru) [inline src/globalshortcuts/globalshortcuts_win.cpp:28]: You need to do the same in "globalshortcuts_linux.cpp". Just pay attention to "eventType" being used in there.

File: src/smplayer.pro [hunk 2]
```diff
@@ -61,6 +61,25 @@ greaterThan(QT_MAJOR_VERSION, 4):greaterThan(QT_MINOR_VERSION, 3) {
...
+    QM_SRC_DIR = $${OUT_PWD}/$${BUILD_SUBDIR}
+    QM_DST_DIR = $${OUT_PWD}/$${BUILD_SUBDIR}/translations
+    QMAKE_POST_LINK += $$quote(cmd /c if not exist $$shell_quote($$replace(QM_DST_DIR,"/","\\")) mkdir $$shell_quote($$replace(QM_DST_DIR,"/","\\")))$$escape_expand(\n\t)
+    QMAKE_POST_LINK += $$quote(cmd /c copy /y $$shell_quote($$replace(QM_SRC_DIR,"/","\\")\\)*.qm $$shell_quote($$replace(QM_DST_DIR,"/","\\")))$$escape_expand(\n\t)
+    QMAKE_CLEAN += $${QM_DST_DIR}/*.qm
+} else {
+    QM_SRC_DIR = $${OUT_PWD}
+    QM_DST_DIR = $${OUT_PWD}/translations
+    QMAKE_POST_LINK += mkdir -p $${QM_DST_DIR}$$escape_expand(\n\t)
+    QMAKE_POST_LINK += cp $${QM_SRC_DIR}/*.qm $${QM_DST_DIR}$$escape_expand(\n\t)
```
Comment (stefantalpalaru) [inline src/smplayer.pro:79]: There's nothing to copy, on Linux, and this errors out.

**Comment by sergiomb2** [comment]
we already have a Qt6 branch: https://github.com/smplayer-dev/smplayer/tree/qt6. I think, but I’m not certain, that you should use it to review the code, identify any issues.

**Comment by stefantalpalaru** [comment]
Thank you. The patch I get from diffing that branch to "master" is better for my Gentoo overlay package: https://github.com/smplayer-dev/smplayer/compare/master...qt6.patch
