### ISSUE TITLE
Release 21.10 broken in macOS 10.14 mojave: mpv symbol not found: _objc_opt_new

### ISSUE THREAD

**Issue by sunrenjie** [smplayer-dev/smplayer#292]
**Describe the bug**

Not sure this bug report shall be issued against https://github.com/smplayer-dev/mpv-mod/
Please build against an older SDK and make it work for older macOS release. Thanks. :)

Release 21.10 broken in macOS 10.14 mojave:
$ /Applications/SMPlayer.app/Contents/MacOS/mpv
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_new
  Referenced from: /Applications/SMPlayer.app/Contents/MacOS/mpv (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_new
  Referenced from: /Applications/SMPlayer.app/Contents/MacOS/mpv (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

Abort trap: 6

**To Reproduce**
1. download the release and run in macOS 10.14 mojave. Same error running in GUI or in command line.

**Expected behavior**
Shall work?

**Screenshots**
None

**Your Enviroment**
 - SMPlayer version: Release 21.10
 - OS: macOS 10.14 mojave
 - Multimedia engine you're using with SMPlayer (preferences -> general): mpv

**Comment by smplayer-dev** [comment]
I'm afraid I don't know how to do that.
Patch is welcome.

**Comment by sunrenjie** [comment]
Hi,
By checksum the mpv in the release is indeed from https://github.com/smplayer-dev/mpv-mod . So we are talking about that repo.

The official mpv works fine in my macOS 10.14 mojave (not with smplayer of course), so some tool chain differences. For the problem here, some refresh from upstream updates works?

I've compiled mpv-mod (with a few mods) in my machine (macOS mojave 10.14.6 with Xcode 11.3.1 + macOS SDK 10.15 + MacPorts to install dependencies), and it works fine with smplayer. A few points:
1. It seems that the macOS SDK version is auto-detected (see waf output). I'm sure I have only SDK 10.15, but it works. There must be something else.
2. The binary probably works only in my machine, as it depends heavily on MacPorts binaries in runtime (as revealed by otool -L). I'm not sure how to make it more compatible with other typical "non-dev" machines.

Building environment seems more relevant here.

**Comment by smplayer-dev** [comment]
mpv-mod is build by a [github action](https://github.com/smplayer-dev/mpv-mod/blob/main/.github/workflows/build-macos.yml) using a macos 10.15 virtual environment. I'm afraid there's no environment for macos 10.14.

I grabbed [this action](https://github.com/jnozsc/mpv-nightly-build/blob/master/.github/workflows/main.yml) that is used to build the mpv nightly builds (compatible with 10.14), however it [fails for me](https://github.com/smplayer-dev/mpv-mod/runs/4333361134?check_suite_focus=true).

**Comment by sunrenjie** [comment]
Thanks for pointing out that. :)
The action fails on libXau.6.dylib, which remains me of the fact that mpv-mod built by github indeeds contains Xorg stuff (which is strange as it is native to Linux GUI but not to Mac), suggesting some "contamination". Neither mpv official nor my local mpv-mod builds contain any X libs (though for me ffmpeg requires some X libs during building). I will try to dig the build scripts to find more hints.

**Comment by smplayer-dev** [comment]
Apparently some of the dependencies have now new dependency packages, and those packages have to be recompiled. I'm trying to identify those packages and fix it. Unfortunately this is very slow because each build takes about 2 or 3 hours to complete.

**Comment by smplayer-dev** [comment]
Could you test if this build works for you? (download the "artifact" at the bottom of the page):
https://github.com/smplayer-dev/mpv-mod/actions/runs/1529819355

**Comment by sunrenjie** [comment]
Sorry for the late reply. It fails with another message now:
$ md5sum mpv
3a27f131b4f001579998dce3c3237511  mpv

$ ./mpv
dyld: lazy symbol binding failed: Symbol not found: _objc_opt_self
  Referenced from: /Users/xxx/Downloads/mpv.app/Contents/MacOS/./mpv
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_opt_self
  Referenced from: /Users/xxx/Downloads/mpv.app/Contents/MacOS/./mpv
  Expected in: /usr/lib/libobjc.A.dylib

Abort trap: 6

**Comment by smplayer-dev** [comment]
I'm afraid I don't know how to fix that error. If anyone knows please let me know.

I compiled mpv-mod in azure pipelines using macos 10.14, I guess [this package](https://github.com/smplayer-dev/macos-stuff/releases/download/test1/mpv.dmg) will work for you. However the macos 10.14 image is deprecated and they're about to remove it, so this is not a solution.

**Comment by smplayer-dev** [comment]
I think the problem is fixed in [this build](https://github.com/smplayer-dev/smplayer/actions/runs/1566303927).
